### ISSUE TITLE
Numbering of sub-chapters

### ISSUE THREAD

**Issue by drgrigg** [mgbennet/e-e-smith_triplanetary#1]
Normally we use roman numerals even for sub-chapters but I see you have used Arabic numerals. Was there a reason for this? Have I missed a discussion with Alex about it?

You have, for example:
```
<section id="chapter-2-2" epub:type="subchapter">
		<h3 epub:type="title">2. Arisia</h3>
```

whereas I would have expected to see:

```
<section id="chapter-2-2" epub:type="subchapter">
		<h3 epub:type="title">
				<span epub:type="z3998:roman">II</span>
				<span epub:type="subtitle">Arisia</span>
		</h3>
```

And of course, the ToC to match.

**Comment by mgbennet** [comment]
Nope, only reason was that was how the scans have them. Fixed.
