### ISSUE TITLE
Abbreviation class "acronym" should be "initialism"

### ISSUE THREAD

**Issue by drgrigg** [mgbennet/e-e-smith_triplanetary#2]
In chapter 5 you have:

`If you ram those substandard <abbr class="acronym">H.E.A.T.</abbr> shell`

According to the Standards Manual 8.10.1 and 8.10.2 I think this should either be an initialism (leaving in the periods) or if it's an acronym the periods should be removed.

**Comment by mgbennet** [comment]
Given that it's pronounced as a word ('heat'), I've left it marked as an acronym and removed the periods.
